_BASE_: [
  '../../datasets/coco_instance_DIY.yml',
  '../../runtime.yml',
  '../_base_/trans_solov2_tem_dcn_fusehead.yml',
  '../_base_/optimizer_1x.yml',
  '../_base_/solov2_reader.yml',
]
# it is a model for comparing to paper model
# there are FPN with a boundary supervised module and fuse head modules in model based on solov2
weights: output/trans_solov2_fpn_boundary_super_4x/45.pdparams
#pretrain_weights: output/trans_solov2_tem_4x/pre_model_final.pdparams
epoch: 48

# using Exponential Moving Average，this will make model more stable
#use_ema: true
#ema_decay: 0.9998

LearningRate:
  base_lr: 0.00085
  schedulers:
  - !PiecewiseDecay
    gamma: 0.3
    milestones: [18, 33, 44]
  - !LinearWarmup
    start_factor: 0.
    #pic_num/batch_size*epoch_num
    steps: 1000

TrainReader:
  sample_transforms:
  - Decode: {}
  - Poly2Mask: {}
  - RandomResize: {interp: 1,
                     target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]],
                     keep_ratio: True}
  - RandomFlip: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  # scale_ranges are all multiples of 32
  - Gt2Solov2Target: {num_grids: [40, 24, 12],
                        scale_ranges: [[1, 192], [16, 448], [384, 3040]],
                        coord_sigma: 0.2}
  batch_size: 2
  shuffle: true
  drop_last: true

TransSolo:
  backbone: Res2Net
  neck: FPN_BS
  solov2_head: TransSOLOv2Head
  mask_head: TransMaskHead

FPN_BS:
  out_channel: 64
